version: '3.9'

services:
  validator-efficiency:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5561:5561"
    restart: always


  prometheus:
    image: prom/prometheus:latest
    command:
      - --web.config.file=web.yml
    ports:
      - "9090:9090"
    environment:
      - PROMETHEUS_DISABLE_CREATED_SERIES=True
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /prometheus/prometheus.yml
        read_only: true
      - type: bind
        source: ./prometheus-web-config.yml
        target: /prometheus/web.yml
        read_only: true
    restart: always


  ton-http-api:
    image: toncenter/ton-http-api
    build:
      context: ton-http-api/ton-http-api
      dockerfile: .docker/Dockerfile
    ports:
      - ${TON_API_HTTP_PORT:-8081}:8081
    environment:
      - TON_API_CACHE_ENABLED
      - TON_API_CACHE_REDIS_ENDPOINT
      - TON_API_CACHE_REDIS_PORT
      - TON_API_CACHE_REDIS_TIMEOUT
      - TON_API_LOGS_JSONIFY
      - TON_API_LOGS_LEVEL
      - TON_API_TONLIB_LITESERVER_CONFIG=/global.config.json
      - TON_API_TONLIB_KEYSTORE=/keystore
      - TON_API_TONLIB_PARALLEL_REQUESTS_PER_LITESERVER=30
      - TON_API_TONLIB_CDLL_PATH=/tonlib/libtonlibjson.so
      - TON_API_TONLIB_REQUEST_TIMEOUT=120
      - TON_API_GET_METHODS_ENABLED
      - TON_API_JSON_RPC_ENABLED
      - TON_API_ROOT_PATH
      - TON_API_WEBSERVERS_WORKERS=5
    restart: unless-stopped
    networks:
      - internal
    secrets:
      - liteserver_config
    command: -c "gunicorn -k uvicorn.workers.UvicornWorker -w ${TON_API_WEBSERVERS_WORKERS} --bind 0.0.0.0:8081 ${TON_API_GUNICORN_FLAGS} pyTON.main:app"
    healthcheck:
        test: curl -sS http://127.0.0.1:8081${TON_API_ROOT_PATH}/healthcheck || echo 1
        interval: 15s
        timeout: 3s
        retries: 12
    volumes:
      - /usr/bin/ton/tonlib/libtonlibjson.so:/tonlib/libtonlibjson.so
      - /usr/bin/ton/global.config.json:/global.config.json


secrets:
  liteserver_config:
    file: ${TON_API_TONLIB_LITESERVER_CONFIG:-/global.config.json}


networks:
  internal: