global:
  scrape_interval: 5m
  evaluation_interval: 5m
  scrape_timeout: 1m

  external_labels:
    watcher: 'validators-efficiency-watcher'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [localhost:9090]

  - job_name: validator_efficiency
    static_configs:
      - targets: ['localhost:5561']
