global:
  scrape_interval: 1m
  evaluation_interval: 1m
  scrape_timeout: 1m

  external_labels:
    watcher: 'validators-efficiency-watcher'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [localhost:9090]
    basic_auth:
      username: admin
      password: admin

  - job_name: validator_efficiency
    static_configs:
      - targets: ['localhost:5561']
